version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 42_eval_viewer
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN:-localhost}
      - NEXT_PUBLIC_42_CLIENT_ID=${NEXT_PUBLIC_42_CLIENT_ID}
      - NEXT_PUBLIC_42_CLIENT_SECRET=${NEXT_PUBLIC_42_CLIENT_SECRET}
      - NEXT_PUBLIC_42_REDIRECT_URI=${NEXT_PUBLIC_42_REDIRECT_URI}
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - 42_eval_data:/app/.next/cache
      - 42_eval_local_storage:/app/.local-storage

volumes:
  42_eval_data:
  42_eval_local_storage:
