import type { Metadata } from "next";
import { GeistSans, GeistMono } from '@vercel/font/core';
import "./globals.css";

const geistSans = GeistSans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

const geistMono = GeistMono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );  );


}}
